DROP FUNCTION IF EXISTS GetAdInfo(INT);
DROP FUNCTION IF EXISTS GetAdsByUser(INT);
DROP FUNCTION IF EXISTS GetUserInfo(INT);
DROP FUNCTION IF EXISTS GetUserChats(INT);
DROP FUNCTION IF EXISTS GetChatMessages(INT);
DROP FUNCTION IF EXISTS GetBookedeDates(INT);

DROP TRIGGER IF EXISTS before_insert_promotion ON Promotion;
DROP TRIGGER IF EXISTS before_insert_message ON Message;
DROP FUNCTION IF EXISTS delete_expired_promotions;
DROP FUNCTION IF EXISTS check_user_chat_access;

DROP TABLE IF EXISTS Message_status;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS Chats;
DROP TABLE IF EXISTS Chat;
DROP TABLE IF EXISTS Favorites;
DROP TABLE IF EXISTS Views;
DROP TABLE IF EXISTS Calendar;
DROP TABLE IF EXISTS Promotion;
DROP TABLE IF EXISTS Ad;
DROP TABLE IF EXISTS Colors;
DROP TABLE IF EXISTS Types;
DROP TABLE IF EXISTS Models;
DROP TABLE IF EXISTS Feedback;
DROP TABLE IF EXISTS Notifications;
DROP TABLE IF EXISTS Notification;
DROP TABLE IF EXISTS Users;